version: '3.8'
# Base configuration that can be extended by dev or prod configurations
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
