spring:
  application:
    name: training-app
  profiles:
    active: local

# Environment indicator
environment:
  name: Local Development
  type: development

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 20

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    syntaxHighlight:
      activated: true
    tagsSorter: alpha
    filter: true
    displayRequestDuration: true
    configUrl: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Documentation
    disable-swagger-default-url: true
    # Custom JavaScript to add environment styling
    urls.primaryName: API Documentation
    supportedSubmitMethods:
      - get
      - post
      - put
      - delete
      - patch
    csrf:
      enabled: true
    docExpansion: none
    validatorUrl: ""
    persistAuthorization: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Application-specific settings
app:
  security:
    jwt:
      secret: ${JWT_SECRET:verySecureJwtSecretKeyThatIsAtLeast32CharactersLong}
      expiration: 86400000 # 24 hours
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
    audit:
      enabled: true
