spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:trainingdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 50

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.training: INFO
    com.example.training.security: WARN

# API documentation - disable in production
springdoc:
  api-docs:
    enabled: ${ENABLE_API_DOCS:false}
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:false}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

# Application-specific settings
app:
  security:
    jwt:
      # In production, this should be set via environment variable
      secret: ${JWT_SECRET}
      expiration: 86400000 # 24 hours
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://example.com}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
    audit:
      enabled: true
