spring:
  # Database configuration for local development
  datasource:
    url: jdbc:postgresql://localhost:5432/trainingdb
    username: postgres
    password: postgres
  
  # Disable flyway migrations for local development
  jpa:
    hibernate:
      ddl-auto: update
  
  # Enable SQL logging
  jpa.properties.hibernate.show_sql: true
  jpa.properties.hibernate.format_sql: true

# Enable all actuator endpoints for local
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging
logging:
  level:
    com.example.training: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO