name: Java CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build and test with Maven
        run: ./mvnw clean test
      
      - name: Build Docker image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        run: |
          chmod +x mvnw
          docker build -t training-app:${{ github.sha }} .
          
      - name: Docker image info
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        run: docker images
