name: Development CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package
    
    - name: Run tests
      run: ./mvnw test
    
    - name: Run integration tests
      run: ./mvnw verify -P integration-test
    
    - name: Build Docker image
      run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
    
    - name: Save test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
    
    - name: Save build artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: target/*.jar

  # Add deployment to development environment if needed
  # deploy-dev:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
  #   
  #   steps:
  #   - name: Deploy to development
  #     run: echo "Deploying to development environment"
